### ISSUE TITLE
App doesn't work with Cyrillic symbols

### ISSUE THREAD

**Issue by DmitriyShahovoy** [andialbrecht/sqlparse#326] opened 2017-03-23 10:23 UTC
Traceback (most recent call last):
  File "/usr/local/bin/sqlformat", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/sqlparse/cli.py", line 177, in main
    stream.write(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5489-5496: ordinal not in range(128)

Stack Trace:

Error: Traceback (most recent call last):
  File "/usr/local/bin/sqlformat", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/sqlparse/cli.py", line 177, in main
    stream.write(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5489-5496: ordinal not in range(128)
    at /home/user/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:295:27
    at tryCatcher (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/it050886sdp/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by andialbrecht** [comment] 2017-03-30 05:29
Which version of sqlformat is this? Could you please run `sqlformat --version`?

**Comment by DmitriyShahovoy** [comment] 2017-03-30 10:50
sqlformat --version
0.2.3

**Comment by hgaronfolo** [comment] 2017-10-17 08:35
I have the same issue with Danish characters æ, ø and å.. Sometimes our developers leave comments in Danish using æ,ø and å.

Error message is the same as DmitriyShahovoy, but I am on version 0.2.4

**Comment by andialbrecht** [comment] 2017-12-20 10:16
Could someone provide a stripped down example file to reproduce this issue on the command line using "sqlformat" directly?

**Comment by JamborJan** [comment] 2018-07-17 12:42
This might be off topic but there is a chance that it helps ...

I get the same error message when I use sqlformat as SQL beautifyer in atom. When I use the exact same file with the `sqlformat -r dummy.sql` it works as expected. 

When I remove `ä`, `ö`, `ü` and `#` it works also in atom beautify. As others replied already: it is not possible to avoid such characters in comments. 

Other circumstances in my case:
- latest macOS
- latest atom editor with up to date beautify plugin
- sql files originally from Windows Machines (AccessDB)

Trace from within atom:
```
Error: Traceback (most recent call last):
  File "/usr/local/bin/sqlformat", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/sqlparse/cli.py", line 180, in main
    stream.write(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\xdc' in position 522: ordinal not in range(128)
    at /Users/jj/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:183:23
    at tryCatcher (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by andialbrecht** [comment] 2018-07-31 06:38
@JamborJan, thanks for the feedback. Closing this issue as it seems to be a problem with atom-beautify.

**Closed by andialbrecht** 2018-07-31 06:38 UTC
